# Generated by Django 5.2.7 on 2025-10-23 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_calorie_goal', models.PositiveIntegerField(default=2000)),
                ('water_goal_glasses', models.PositiveIntegerField(default=8)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
